#!/bin/bash
set -e

distro=debian

source /root/dnc/dnclib-newguest-args
source /etc/dnc.conf
source /root/dnc/dnclib
source /root/dnc/dnclib-checks
source /root/dnc/dnclib-newguest-checks
source /root/dnc/dnclib-newguest-postinstall

# todo - use absolute path all script long instead of entering the folder
cd $data/guests/$res/

# assuming no fstab (like you simply did deboostrap and that's it!)
# todo - deal with butterfs and reiser4
echo -n static filesystems information ...
cat > lala/etc/fstab <<EOF && echo done
/dev/xvda1 / ext4 defaults 0 1
devpts /dev/pts devpts gid=5,mode=620 0 0
tmpfs /tmp tmpfs rw,nodev,nosuid,noatime,relatime 0 0
proc /proc proc defaults 0 0
EOF
#/dev/xvda1 / btrfs rw,noatime,nodiratime,space_cache=v2,compress=lzo,discard 0 0

echo -n hostname $short ...
echo $short > lala/etc/hostname && echo done

# ip got defined by dec2ip
#echo -n tuning /etc/hosts ...
#echo 127.0.0.1 localhost.localdomain localhost > lala/etc/hosts
#echo ::1 localhost.localdomain localhost >> lala/etc/hosts
#echo ${ip%/*} $short.localdomain $short >> lala/etc/hosts
#[[ -n $gw ]] && echo $gw gw.localdomain gw >> lala/etc/hosts && echo done

# here sourcing var names, not vars themselves (requires BASH)
#echo adding dns entries to /etc/hosts
#for dns in dns1 dns2 dns3 dns4; do
#        [[ -n ${!dns} ]] && echo ${!dns} $dns >> lala/etc/hosts
#done; unset dns

echo -n static names ...
cat > lala/etc/hosts <<EOF && echo done
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

$ip		$short
EOF
#$dns0 dns0

source /root/dnc/dnclib-newguest-resolv

echo -n network setup ...
cat > lala/etc/network/interfaces <<EOF && echo done
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address $ip/16
	gateway $gw
EOF

source /root/dnc/dnclib-newguest-sshd

# todo - let the system generate its key pars at first boot?
#	 that would be better

# [FAILED] Failed to start OpenBSD Secure Shell server.
# we have better entropy on bare-metal anyway
#ssh-keygen -q -t dsa -f lala/etc/ssh/ssh_host_dsa_key -C root@$short -N ''
#ssh-keygen -q -t rsa -f lala/etc/ssh/ssh_host_rsa_key -C root@$short -N ''
echo generating ECC-only ssh host keys
ssh-keygen -q -t ecdsa -f lala/etc/ssh/ssh_host_ecdsa_key -C root@$short -N ''
ssh-keygen -q -t ed25519 -f lala/etc/ssh/ssh_host_ed25519_key -C root@$short -N ''

# ADDITIONAL FIXUP - template out of sync
#echo -n writing sources.list ...
#cat > lala/etc/apt/sources.list <<EOF && echo done
#deb http://ftp.ro.debian.org/debian/ bullseye main contrib non-free
#deb http://ftp.ro.debian.org/debian/ bullseye-updates main contrib non-free
#deb http://ftp.ro.debian.org/debian/ bullseye-backports main contrib non-free
#deb http://security.debian.org/debian-security bullseye-security main contrib non-free
#EOF

source /root/dnc/dnclib-newguest-ready

