#!/bin/bash
set -e

# todo - trap un-mount $data/guests/$res/lala in case of failure

#
# no need for $tpl here since we already defined that while cloning the origin snapshot
#

[[ -z $1 ]] && echo usage: "${0##*/} <drbd slot> [guest hostname]" && exit 1
slot=$1

# use standardized name if not provided
# note that only matters for within the systems itself
# we otherwise strictly use drbd resource name from our infrastructure layer
[[ -n $2 ]] && guest=$2 || guest=dnc$slot

# fix guest hostname just in case fqdn was provided
short=${guest%%\.*}

source /etc/dnc.conf
source /root/dnc/dnclib

# check drbd/lvm resource status
# defines $res
source /root/dnc/dnclib-checks

# provided as args
[[ -z $slot ]]  && bomb missing \$slot
[[ -z $guest ]] && bomb missing \$guest

# shorthands
[[ -z $short ]] && bomb missing \$short

# provided by dnclib-checks
[[ -z $res ]]   && bomb missing \$res

alive=`dsh -e -g xen "xl list | grep -E \"^$res[[:space:]]+\"" | cut -f1 -d:`
[[ -n $alive ]] && echo $res already lives on $alive && exit 1

# gw and friends got sourced by dnc.conf
# but guest ip gets eveluated by dec2ip function
dec2ip $slot

[[ -z $ip ]] && bomb missing \$ip
[[ -z $gw ]] && bomb missing \$gw

echo
echo DEBIAN SYSTEM POST-INSTALLATION
echo

# note drbd resource is possibly diskless

mkdir -p $data/guests/$res/lala/

# we have two kinds of debian templates BTRFS and REISER4
#btrfs check --readonly /dev/drbd/by-res/$res/0 >/dev/null 2>&1 && fs=btrfs || fs=reiser4
#dd if=/dev/drbd/by-res/$res/0 bs=1M count=1 2>/dev/null | hexdump -C | grep BHRfS >/dev/null 2>&1 && fs=btrfs || fs=reiser4

function mount__ext4 {
	echo -n mount ext4 ...
	mount -t ext4 /dev/drbd$slot $data/guests/$res/lala/ && \
		echo done || bomb failed to mount ext4 for $res drbd resource
}

function mount__btrfs {
	echo mounting butterfs ...
	mount -t btrfs -o compress=lzo /dev/drbd$slot $data/guests/$res/lala/
	# (already resized)
	# not sure why that command doesn't return 0 although it succeeds
}

function mount__reiser4 {
	echo -n mounting reiser4 ...
	mount -t reiser4 -o noatime,nodiratime,txmod=wa,discard \
		/dev/drbd$slot $data/guests/$res/lala/ && \
		echo done || bomb failed to mount reiser4 for $res
	# async
}

#[[ ! -x `which btrfs` ]] && bomb missing btrfs command

echo checking filesystem type
if tune2fs -l /dev/drbd$slot >/dev/null >/dev/null 2>&1; then
	mount__ext4
elif btrfs filesystem show /dev/drbd$slot >/dev/null 2>&1; then
	mount__btrfs
else
	mount__reiser4
fi

# todo - use absolute path all script long instead of entering the folder
cd $data/guests/$res/

# assuming no fstab (like you simply did deboostrap and that's it!)
# todo - deal with butterfs and reiser4
echo -n static filesystems information ...
cat > lala/etc/fstab <<EOF && echo done
/dev/xvda1 / ext4 defaults 0 1
devpts /dev/pts devpts gid=5,mode=620 0 0
tmpfs /tmp tmpfs rw,nodev,nosuid,noatime,relatime 0 0
proc /proc proc defaults 0 0
EOF
#/dev/xvda1 / btrfs rw,noatime,nodiratime,space_cache=v2,compress=lzo,discard 0 0

echo -n hostname $short ...
echo $short > lala/etc/hostname && echo done

# ip got defined by dec2ip
#echo -n tuning /etc/hosts ...
#echo 127.0.0.1 localhost.localdomain localhost > lala/etc/hosts
#echo ::1 localhost.localdomain localhost >> lala/etc/hosts
#echo ${ip%/*} $short.localdomain $short >> lala/etc/hosts
#[[ -n $gw ]] && echo $gw gw.localdomain gw >> lala/etc/hosts && echo done

# here sourcing var names, not vars themselves (requires BASH)
#echo adding dns entries to /etc/hosts
#for dns in dns1 dns2 dns3 dns4; do
#        [[ -n ${!dns} ]] && echo ${!dns} $dns >> lala/etc/hosts
#done; unset dns

echo -n writing hosts ...
cat > lala/etc/hosts <<EOF && echo done
127.0.0.1       localhost.localdomain localhost
::1             localhost.localdomain localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

${ip%/*}	$short

EOF
#$dns0 dns0

# same here, no network setup assumed in the template
rm -f lala/etc/resolv.conf

# todo - also add search domain in here
echo -n static name resolution ...
# sourcing the vars themselves
for dns in $dns1 $dns2 $dns3 $dns4; do
        echo nameserver $dns >> lala/etc/resolv.conf
done && echo done; unset dns

#cat > lala/etc/resolv.conf <<EOF && echo done
#nameserver 208.67.222.222
#nameserver 208.67.220.220
#nameserver 10.1.255.253
#nameserver 10.1.255.252
#nameserver 10.1.255.251
#EOF

echo -n network/interfaces ...
cat > lala/etc/network/interfaces <<EOF && echo done
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
	address $ip/16
	gateway $gw

EOF

# before tackling /etc/ssh/...
echo -n make sure openssh-server is installed ...
chroot lala/ which sshd

# just in case template had host keys within (it shouldn't)
#echo clean-up ssh host keys - just in case
rm -f lala/etc/ssh/ssh_host_*

# [FAILED] Failed to start OpenBSD Secure Shell server.
# we have better entropy on bare-metal anyway
#ssh-keygen -q -t dsa -f lala/etc/ssh/ssh_host_dsa_key -C root@$short -N ''
#ssh-keygen -q -t rsa -f lala/etc/ssh/ssh_host_rsa_key -C root@$short -N ''
echo generating ECC-only ssh host keys
ssh-keygen -q -t ecdsa -f lala/etc/ssh/ssh_host_ecdsa_key -C root@$short -N ''
ssh-keygen -q -t ed25519 -f lala/etc/ssh/ssh_host_ed25519_key -C root@$short -N ''

echo -n adding user ssh authorized pubkeys ...
mkdir -p lala/root/.ssh/
cat > lala/root/.ssh/authorized_keys <<EOF && echo done
$pubkeys
EOF
chmod 700 lala/root/.ssh/
chmod 600 lala/root/.ssh/authorized_keys

# ADDITIONAL FIXUP - template out of sync
#echo -n writing sources.list ...
#cat > lala/etc/apt/sources.list <<EOF && echo done
#deb http://ftp.ro.debian.org/debian/ bullseye main contrib non-free
#deb http://ftp.ro.debian.org/debian/ bullseye-updates main contrib non-free
#deb http://ftp.ro.debian.org/debian/ bullseye-backports main contrib non-free
#deb http://security.debian.org/debian-security bullseye-security main contrib non-free
#EOF

echo -n empty the root password ...
chroot lala/ passwd -d root

#
# done tuning the guest image
#

echo -n un-mounting...
umount $data/guests/$res/lala/ && echo done
rmdir $data/guests/$res/lala/

echo -n writing guest config...
cat > $data/guests/$res/$res <<EOF && echo done
kernel = "$data/kernels/5.2.21.domureiser4.vmlinuz"
root = "/dev/xvda1 ro console=hvc0 net.ifnames=0 biosdevname=0 mitigations=off"
#extra = "init=/bin/bash"
name = "$res"
vcpus = 1
memory = 1024
disk = ['phy:/dev/drbd$slot,xvda1,w']
vif = [ 'bridge=guestbr0, vifname=dnc$slot.0',
	'bridge=guestbr0, vifname=dnc$slot.1' ]
EOF

# we want PV not PVH when doing PoC as nested
[[ $pvh = yes ]] && echo 'type = "pvh"' >> $data/guests/$res/$res

#memory = 7168
# netcfg/do_not_use_netplan=true
echo

#echo starting guest $guest
#xl create $data/guests/$guest/$guest && echo -e \\nGUEST $guest HAS BEEN STARTED
#echo up > $data/guests/$guest/state
/root/dnc/dnc-startguest-lowram $res

